"""phase3_schema

Revision ID: 828ca2876536
Revises: 8f43abbc39a8
Create Date: 2026-04-09 17:53:10.664687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828ca2876536'
down_revision: Union[str, Sequence[str], None] = '8f43abbc39a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('news_articles', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('news_articles', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.alter_column('news_articles', 'ticker',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('uq_news_url'), 'news_articles', type_='unique')
    op.create_unique_constraint(None, 'news_articles', ['content_hash'])
    op.drop_column('news_articles', 'headline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('headline', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news_articles', type_='unique')
    op.create_unique_constraint(op.f('uq_news_url'), 'news_articles', ['url'], postgresql_nulls_not_distinct=False)
    op.alter_column('news_articles', 'ticker',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('news_articles', 'content_hash')
    op.drop_column('news_articles', 'summary')
    op.drop_column('news_articles', 'title')
    # ### end Alembic commands ###
